language: python
arch:
    - amd64
    - ppc64le
addons:
    apt:
       update: true
       packages: 
           - build-essential 
           - libssl-dev 
           - libffi-dev 
           - python3-dev
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6.3" # Using specific subversion of 3.6 which was working earlier.
    - "3.7" # Using the stable version of 3.7
    - "nightly" # currently points to 3.7-dev
install:
    - git submodule init
    - git submodule update
    # master of submodule contains differen number of english words which makes the test fail
    # Commenting it
    #- git submodule foreach git pull origin master
    - pip install -U setuptools coveralls
    - python bootstrap.py
    - ./bin/buildout
before_script:
    - ./bin/flake8 stop_words
script:
    - ./bin/cover
notifications:
    irc:
        - "irc.freenode.org#python-stop-words"
after_success:
    coveralls
